import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers/providers";
import CustomNavbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";

const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Steven Zuluaga Cortés",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={`${inter.className} `}>

        <Providers>
          <CustomNavbar />
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
